### ISSUE TITLE
Iniciacion de actividades y creacion del modelo

### ISSUE THREAD

**Issue by arespinoza** [dorlandoc/HeladeriaMAC-D#1]
En esta actividad se espera que se suban las clases del modelo. Puede acompañar de un diagrama de clases si es que tienen los conocimientos para su desarrollarlo. Tiempo estimado para la actividad tres días.

**Comment by arespinoza** [comment]
La clase pedido en la ultima version que se comiteo por parte de ustedes, no tiene asignado los productos que se pidieron por parte del usuario. Esto puede representarse por un array de DetallePedido donde esta clase tendra entre otras cosas la el producto pedido, la cantidad, precio aplicado. Osea que Pedido tendra un atributo que sera de tipo array, un array de DetallePedido. Falta aplicar en el modelo las promociones que tiene igual interpretacion. una promocion puede englobar a varios productos, cada uno con su nuevo precio y otros atributos mas. revisar integramente el modelo

**Comment by Lhyck** [comment]
![IMG_20190608_125054012](https://user-images.githubusercontent.com/38406571/59150942-7855cc80-8a01-11e9-9cf0-27921eda1b19.jpg)
Profesor masomens asi seria el diseño

**Comment by arespinoza** [comment]
Hola buenos dias la parte de abajo se puede interpretar claramente, la de arriba esta bastante borrosa, por favor si alguien puede estare en clases de consulta a las 14:30 en ingenieria. por lo pronto puedo decirte de lo que se puede observar Un PEIDIDO puede tener varios PRODUCTO-PEDIDO pero esa relacion es de uno a N. y en el DER esta al reves en el diagrama. Igual quisiera que me lo muestren y expliquen personalmente para no entrarn en confusiones. De la misma manera pareceria que la relacion de PRODUCTO Y PRODOCTO-PEDIDO SERIA AL REVES. Saludos los espero.
